#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import sys

from schwarz.borgprune import cli


if __name__ == '__main__':
	if len(sys.argv) != 2:
		sys.stderr.write('usage: %s BORGREPO\n' % sys.argv[0])
		sys.exit(1)
	borgrepo = sys.argv[1]
	cli.prune_repo(borgrepo, dry_run=False, verbose=True)
